version: '3.8'

services:
  api:
    build: .
    container_name: logishift_api
    restart: always
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@host:5432/db_name
      - JWT_SECRET=your_secret_key
    networks:
      - smenabot_net
    volumes:
      - /opt/docker-data/static_files:/app/uploads
    ports:
      - "3000:3000"

networks:
  smenabot_net:
    external: true
    name: smenabot-net
